FROM python:3-alpine

LABEL maintainer "florian.stosse@safrangroup.com"
LABEL lastupdate '28-02-2020'
LABEL author "Florian Stosse"
LABEL vendor "Safran Data Systems"
LABEL license "MIT license"

RUN pip install cpplint