FROM python:3.8-alpine

LABEL maintainer "florian.stosse@safrangroup.com"
LABEL lastupdate '25-03-2020'
LABEL author "Florian Stosse"
LABEL description "FlawFinder v2.0.11, built using Python v3.8 Alpine-based image"
LABEL license "MIT license"

RUN pip3 install flawfinder==2.0.11